{"uuid": "abf80b38-4504-4316-8156-99ac83d35e6a", "children": ["f09eae71-756d-452d-bb3b-56bfc568b3b7"], "befores": [{"name": "page", "status": "passed", "start": 1715351943482, "stop": 1715351943575}], "afters": [{"name": "page::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Dima\\Desktop\\Testing\\Python_Playwright\\ZegarowniaProject\\conftest.py\", line 30, in page\n    if request.node.rep_call and request.node.rep_call.failed:\n"}, "start": 1715351943579, "stop": 1715351943594}], "start": 1715351943482, "stop": 1715351943594}