{"uuid": "3d964640-61f6-4440-9153-0b6e070ec8b7", "children": ["253ce5e5-27c8-4206-89fa-089c87816ae0"], "befores": [{"name": "page", "status": "passed", "start": 1715588971500, "stop": 1715588971588}], "afters": [{"name": "page::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Dima\\Desktop\\Testing\\Python_Playwright\\ZegarowniaProject\\conftest.py\", line 30, in page\n    if request.node.rep_call and request.node.rep_call.failed:\n"}, "start": 1715589010497, "stop": 1715589010532}], "start": 1715588971500, "stop": 1715589010532}